// ============================================================
// Gigi's Playhouse — Seed Data
// 6 starter lessons (1 per domain) + 50 flashcards
// ============================================================

import type { Lesson, Flashcard } from './types';

export const SEED_LESSONS: Lesson[] = [
  {
    id: 'literacy-g1-int-d1',
    domain: 'literacy',
    grade_band: 'grade-1',
    difficulty: 'intermediate',
    day_number: 1,
    title: 'The Letter Detective',
    theme: 'Letter Sounds & Phonics',
    episode: {
      title: 'Sounds All Around',
      description: 'Today we become letter detectives! We will listen for beginning sounds in everyday words and discover how letters make special sounds. Get ready to use your super listening ears!',
      duration_minutes: 8,
      skill_tags: ['phonics', 'letter-sounds', 'listening'],
      search_term: 'letter sounds for kids phonics',
    },
    activity: {
      title: 'Sound Hunt Safari',
      instructions: [
        'Grab a piece of paper and a crayon or pencil.',
        'Walk around your home and find 5 things that start with the letter B.',
        'Draw a picture of each thing you find.',
        'Say the name of each thing out loud, stretching out the /b/ sound: "Buh-buh-BALL!"',
        'Circle your favorite B-word drawing!',
      ],
      materials: ['Paper', 'Crayons or pencils'],
      short_version: 'Find 3 things that start with B and draw them.',
    },
    apply_prompt: 'Go to your kitchen and find something that starts with the letter S. Tell a grown-up what you found!',
    reflection_prompt: 'What was the hardest sound to find today?',
    reflect_script: [
      'What letter sound did we practice today?',
      'Can you think of a word that starts with /b/ that we didn\'t find?',
      'What was your favorite thing you found on your Sound Hunt?',
      'Can you make the /b/ sound three times really fast?',
    ],
    quiz: [
      { question: 'Which word starts with the /b/ sound?', type: 'multiple-choice', options: ['Cat', 'Ball', 'Dog', 'Fish'], correct_answer: 1, explanation: 'Ball starts with the /b/ sound — buh-buh-Ball!' },
      { question: 'The word "Sun" starts with the /s/ sound.', type: 'true-false', options: ['True', 'False'], correct_answer: 0, explanation: 'Yes! Sun starts with /s/ — sss-Sun!' },
      { question: 'Which letter makes the "mmmm" sound?', type: 'multiple-choice', options: ['B', 'T', 'M', 'K'], correct_answer: 2, explanation: 'M makes the "mmmm" sound, like in "Mom" and "Moon"!' },
    ],
    on_track_goal: 'Identify beginning sounds in 5 common words',
    stretch_goal: 'Write the beginning letter for 3 words independently',
    asl_word: 'Book',
    materials_needed: ['Paper', 'Crayons or pencils'],
  },
  {
    id: 'math-g1-int-d1',
    domain: 'math',
    grade_band: 'grade-1',
    difficulty: 'intermediate',
    day_number: 1,
    title: 'Counting Critters',
    theme: 'Numbers & Counting to 20',
    episode: {
      title: 'Numbers Are Everywhere',
      description: 'Justin Jr is excited to count everything today! We will practice counting objects up to 20 and learn that numbers tell us "how many." Let\'s see how high we can count!',
      duration_minutes: 7,
      skill_tags: ['counting', 'number-recognition', 'one-to-one-correspondence'],
      search_term: 'counting to 20 for kids',
    },
    activity: {
      title: 'Kitchen Counter Challenge',
      instructions: [
        'Go to your kitchen with a grown-up.',
        'Count how many spoons are in the drawer. Write the number down.',
        'Count how many cups you can see. Write that number too.',
        'Find something you have MORE than 10 of. Count them carefully!',
        'Make a tower of 15 small items (crackers, blocks, or coins). Count as you stack!',
      ],
      materials: ['Kitchen items', 'Paper', 'Pencil'],
      short_version: 'Count spoons in your kitchen and write the number.',
    },
    apply_prompt: 'Count the steps from your bedroom to the kitchen. How many steps did you take?',
    reflection_prompt: 'What was the biggest number you counted today?',
    reflect_script: [
      'What was the biggest number you counted today?',
      'Was it easy or tricky to count past 10?',
      'Can you count backwards from 10 to 1? Let\'s try!',
      'Where do you see numbers in your house?',
    ],
    quiz: [
      { question: 'What number comes after 12?', type: 'multiple-choice', options: ['11', '13', '14', '10'], correct_answer: 1, explanation: '13 comes right after 12! Great counting!' },
      { question: '15 is more than 10.', type: 'true-false', options: ['True', 'False'], correct_answer: 0, explanation: 'Yes! 15 is 5 more than 10.' },
      { question: 'How many fingers do you have on both hands?', type: 'multiple-choice', options: ['5', '8', '10', '20'], correct_answer: 2, explanation: 'You have 10 fingers — 5 on each hand!' },
    ],
    on_track_goal: 'Count objects accurately up to 20',
    stretch_goal: 'Write numbers 1-20 independently',
    asl_word: 'Count',
    materials_needed: ['Kitchen items', 'Paper', 'Pencil'],
  },
  {
    id: 'science-g1-int-d1',
    domain: 'science',
    grade_band: 'grade-1',
    difficulty: 'intermediate',
    day_number: 1,
    title: 'Weather Watchers',
    theme: 'Weather & Seasons',
    episode: {
      title: 'What\'s the Weather Today?',
      description: 'Rachel wants to know — what\'s happening outside your window right now? Today we learn about different types of weather and how to observe like a real scientist. Grab your scientist eyes!',
      duration_minutes: 8,
      skill_tags: ['observation', 'weather', 'recording-data'],
      search_term: 'weather for kids science',
    },
    activity: {
      title: 'My Weather Journal',
      instructions: [
        'Look out your window right now. What do you see?',
        'Draw the sky — is it sunny, cloudy, rainy, or snowy?',
        'Draw what people outside are wearing. Does that tell you about the weather?',
        'Feel the air if you can step outside safely. Is it warm, cool, or cold?',
        'Write or draw one word that describes today\'s weather.',
      ],
      materials: ['Paper', 'Crayons', 'Window to look out of'],
      short_version: 'Draw what the sky looks like right now and write one weather word.',
    },
    apply_prompt: 'Check the weather tomorrow morning and compare it to today. Was it the same or different?',
    reflection_prompt: 'What\'s your favorite type of weather and why?',
    reflect_script: [
      'What was the weather like today?',
      'How did you figure out what the weather was?',
      'What\'s your favorite kind of weather?',
      'What do scientists do when they want to learn about something?',
      'Can you name three types of weather?',
    ],
    quiz: [
      { question: 'Which is NOT a type of weather?', type: 'multiple-choice', options: ['Sunny', 'Rainy', 'Purple', 'Snowy'], correct_answer: 2, explanation: 'Purple is a color, not a type of weather! Weather includes sunny, rainy, snowy, cloudy, and windy.' },
      { question: 'Scientists observe things carefully to learn about them.', type: 'true-false', options: ['True', 'False'], correct_answer: 0, explanation: 'Yes! Observing means looking carefully, and that\'s what scientists do!' },
      { question: 'What do we wear when it\'s rainy?', type: 'multiple-choice', options: ['Swimsuit', 'Rain coat', 'Shorts', 'Sandals'], correct_answer: 1, explanation: 'A rain coat keeps us dry when it rains!' },
    ],
    on_track_goal: 'Identify and describe 3 types of weather',
    stretch_goal: 'Keep a 3-day weather journal with drawings',
    asl_word: 'Weather',
    materials_needed: ['Paper', 'Crayons', 'Window'],
  },
  {
    id: 'social-studies-g1-int-d1',
    domain: 'social-studies',
    grade_band: 'grade-1',
    difficulty: 'intermediate',
    day_number: 1,
    title: 'My Neighborhood Map',
    theme: 'Community & Places',
    episode: {
      title: 'Where Do You Live?',
      description: 'Jamie is exploring the neighborhood today! We\'ll learn about the different places in a community and why they\'re important. Every neighborhood is special — let\'s discover yours!',
      duration_minutes: 7,
      skill_tags: ['community', 'geography', 'mapping'],
      search_term: 'community helpers neighborhood for kids',
    },
    activity: {
      title: 'Draw Your Neighborhood',
      instructions: [
        'Get a big piece of paper and lay it flat.',
        'Draw your home in the middle of the paper.',
        'Draw the road or street near your home.',
        'Add 3 places you know near your home (park, store, school, friend\'s house).',
        'Label each place with its name or draw what happens there.',
      ],
      materials: ['Large paper', 'Crayons or markers'],
      short_version: 'Draw your home and two places near it.',
    },
    apply_prompt: 'Next time you go outside, count how many different buildings you can see from your home.',
    reflection_prompt: 'What\'s your favorite place in your neighborhood?',
    reflect_script: [
      'What places did you put on your map?',
      'Who are some helpers in your neighborhood?',
      'What makes your neighborhood special?',
      'If you could add one new place to your neighborhood, what would it be?',
    ],
    quiz: [
      { question: 'Which is a place you might find in a neighborhood?', type: 'multiple-choice', options: ['The moon', 'A park', 'The ocean floor', 'A volcano'], correct_answer: 1, explanation: 'Parks are wonderful places in neighborhoods where people play and relax!' },
      { question: 'A map shows us where places are.', type: 'true-false', options: ['True', 'False'], correct_answer: 0, explanation: 'Yes! Maps help us find places and see where things are.' },
      { question: 'Who helps keep your neighborhood safe?', type: 'multiple-choice', options: ['Astronauts', 'Firefighters', 'Penguins', 'Robots'], correct_answer: 1, explanation: 'Firefighters are community helpers who keep neighborhoods safe!' },
    ],
    on_track_goal: 'Identify 3 places in their community',
    stretch_goal: 'Create a detailed neighborhood map with 5+ locations',
    asl_word: 'Home',
    materials_needed: ['Large paper', 'Crayons or markers'],
  },
  {
    id: 'sel-g1-int-d1',
    domain: 'social-emotional',
    grade_band: 'grade-1',
    difficulty: 'intermediate',
    day_number: 1,
    title: 'Feelings Friends',
    theme: 'Identifying Emotions',
    episode: {
      title: 'How Are You Feeling Today?',
      description: 'Kaylah wants to check in with you! Today we learn that ALL feelings are okay — happy, sad, angry, scared, excited. The important thing is knowing what we feel and what to do about it.',
      duration_minutes: 6,
      skill_tags: ['emotions', 'self-awareness', 'vocabulary'],
      search_term: 'feelings and emotions for kids',
    },
    activity: {
      title: 'Feelings Face Gallery',
      instructions: [
        'Get 5 small pieces of paper (or cut one big one into 5).',
        'On each paper, draw a face showing a different feeling: happy, sad, angry, scared, surprised.',
        'Under each face, write the feeling word (or have a grown-up help).',
        'Hold up each face and make that expression with YOUR face!',
        'Pick the face that shows how you feel RIGHT NOW and tell someone why.',
      ],
      materials: ['Paper', 'Crayons or markers', 'Scissors (with adult help)'],
      short_version: 'Draw 3 feeling faces and tell someone how you feel today.',
    },
    apply_prompt: 'Before bed tonight, tell someone one thing that made you happy today and one thing that was hard.',
    reflection_prompt: 'Is it okay to feel sad sometimes?',
    reflect_script: [
      'How many different feelings did we talk about today?',
      'Is it okay to feel angry sometimes?',
      'What can you do when you feel scared?',
      'Who can you talk to when you have big feelings?',
      'What feeling face was the most fun to draw?',
    ],
    quiz: [
      { question: 'Is it okay to feel sad sometimes?', type: 'true-false', options: ['True', 'False'], correct_answer: 0, explanation: 'Yes! ALL feelings are okay. It\'s what we DO with our feelings that matters.' },
      { question: 'Which is a feeling?', type: 'multiple-choice', options: ['Purple', 'Excited', 'Sandwich', 'Tuesday'], correct_answer: 1, explanation: 'Excited is a feeling! It\'s when you feel happy and can\'t wait for something.' },
      { question: 'What can you do when you feel angry?', type: 'multiple-choice', options: ['Hit someone', 'Take deep breaths', 'Break things', 'Scream forever'], correct_answer: 1, explanation: 'Taking deep breaths helps calm our bodies when we feel angry. Breathe in... and out...' },
    ],
    on_track_goal: 'Name and identify 5 basic emotions',
    stretch_goal: 'Describe a personal experience for each emotion',
    asl_word: 'Happy',
    materials_needed: ['Paper', 'Crayons or markers', 'Scissors'],
  },
  {
    id: 'exec-g1-int-d1',
    domain: 'executive-function',
    grade_band: 'grade-1',
    difficulty: 'intermediate',
    day_number: 1,
    title: 'Plan It, Do It!',
    theme: 'Planning & Organization',
    episode: {
      title: 'Making a Plan',
      description: 'Darian has a secret superpower — planning! Today we learn that doing things in order makes everything easier. When we plan first, we can do amazing things. Let\'s make our first plan together!',
      duration_minutes: 7,
      skill_tags: ['planning', 'sequencing', 'organization'],
      search_term: 'planning and organization for kids',
    },
    activity: {
      title: 'My Morning Plan',
      instructions: [
        'Think about what you do every morning when you wake up.',
        'Draw or write 5 things you do in the morning (wake up, brush teeth, eat breakfast, etc.).',
        'Cut them out or number them 1-5 in the order you do them.',
        'Mix them up and try to put them back in order!',
        'Show your plan to a grown-up and see if they do things in the same order.',
      ],
      materials: ['Paper', 'Crayons', 'Scissors (optional)'],
      short_version: 'Draw 3 things you do every morning in order.',
    },
    apply_prompt: 'Tomorrow morning, follow your plan! Check off each step as you do it.',
    reflection_prompt: 'Why is it helpful to do things in order?',
    reflect_script: [
      'What was the first thing on your morning plan?',
      'What happens if you try to eat breakfast before you wake up? (That\'s silly!)',
      'Why is it helpful to have a plan?',
      'Can you think of something else you could make a plan for?',
    ],
    quiz: [
      { question: 'What should you do FIRST in the morning?', type: 'multiple-choice', options: ['Go to sleep', 'Wake up', 'Eat dinner', 'Go to school'], correct_answer: 1, explanation: 'You have to wake up first before you can do anything else!' },
      { question: 'Having a plan helps us do things in order.', type: 'true-false', options: ['True', 'False'], correct_answer: 0, explanation: 'Yes! Plans help us know what to do first, next, and last.' },
      { question: 'Which comes first: brush teeth or eat breakfast?', type: 'multiple-choice', options: ['Brush teeth', 'It depends on your plan!', 'Neither', 'Both at the same time'], correct_answer: 1, explanation: 'Great thinking! Different families have different plans, and that\'s okay!' },
    ],
    on_track_goal: 'Create a simple 5-step sequence',
    stretch_goal: 'Follow a self-made plan independently for one day',
    asl_word: 'Plan',
    materials_needed: ['Paper', 'Crayons', 'Scissors'],
  },
];

// 50 seed flashcards — alphabet phonics A-Z + extras
export const SEED_FLASHCARDS: Flashcard[] = [
  { id: 'fc-a', domain: 'literacy', front: 'A', back: 'Apple', phonics_notation: '/æ/ — ah — Apple', emoji: '🍎' },
  { id: 'fc-b', domain: 'literacy', front: 'B', back: 'Ball', phonics_notation: '/b/ — buh — Ball', emoji: '⚽' },
  { id: 'fc-c', domain: 'literacy', front: 'C', back: 'Cat', phonics_notation: '/k/ — kuh — Cat', emoji: '🐱' },
  { id: 'fc-d', domain: 'literacy', front: 'D', back: 'Dog', phonics_notation: '/d/ — duh — Dog', emoji: '🐕' },
  { id: 'fc-e', domain: 'literacy', front: 'E', back: 'Elephant', phonics_notation: '/ɛ/ — eh — Elephant', emoji: '🐘' },
  { id: 'fc-f', domain: 'literacy', front: 'F', back: 'Fish', phonics_notation: '/f/ — fuh — Fish', emoji: '🐟' },
  { id: 'fc-g', domain: 'literacy', front: 'G', back: 'Giraffe', phonics_notation: '/g/ — guh — Giraffe', emoji: '🦒' },
  { id: 'fc-h', domain: 'literacy', front: 'H', back: 'Hat', phonics_notation: '/h/ — huh — Hat', emoji: '🎩' },
  { id: 'fc-i', domain: 'literacy', front: 'I', back: 'Igloo', phonics_notation: '/ɪ/ — ih — Igloo', emoji: '🏠' },
  { id: 'fc-j', domain: 'literacy', front: 'J', back: 'Juice', phonics_notation: '/dʒ/ — juh — Juice', emoji: '🧃' },
  { id: 'fc-k', domain: 'literacy', front: 'K', back: 'Kite', phonics_notation: '/k/ — kuh — Kite', emoji: '🪁' },
  { id: 'fc-l', domain: 'literacy', front: 'L', back: 'Lion', phonics_notation: '/l/ — luh — Lion', emoji: '🦁' },
  { id: 'fc-m', domain: 'literacy', front: 'M', back: 'Moon', phonics_notation: '/m/ — mmm — Moon', emoji: '🌙' },
  { id: 'fc-n', domain: 'literacy', front: 'N', back: 'Nest', phonics_notation: '/n/ — nuh — Nest', emoji: '🪺' },
  { id: 'fc-o', domain: 'literacy', front: 'O', back: 'Octopus', phonics_notation: '/ɒ/ — ah — Octopus', emoji: '🐙' },
  { id: 'fc-p', domain: 'literacy', front: 'P', back: 'Penguin', phonics_notation: '/p/ — puh — Penguin', emoji: '🐧' },
  { id: 'fc-q', domain: 'literacy', front: 'Q', back: 'Queen', phonics_notation: '/kw/ — kwuh — Queen', emoji: '👑' },
  { id: 'fc-r', domain: 'literacy', front: 'R', back: 'Rainbow', phonics_notation: '/r/ — ruh — Rainbow', emoji: '🌈' },
  { id: 'fc-s', domain: 'literacy', front: 'S', back: 'Sun', phonics_notation: '/s/ — sss — Sun', emoji: '☀️' },
  { id: 'fc-t', domain: 'literacy', front: 'T', back: 'Tree', phonics_notation: '/t/ — tuh — Tree', emoji: '🌳' },
  { id: 'fc-u', domain: 'literacy', front: 'U', back: 'Umbrella', phonics_notation: '/ʌ/ — uh — Umbrella', emoji: '☂️' },
  { id: 'fc-v', domain: 'literacy', front: 'V', back: 'Violin', phonics_notation: '/v/ — vuh — Violin', emoji: '🎻' },
  { id: 'fc-w', domain: 'literacy', front: 'W', back: 'Whale', phonics_notation: '/w/ — wuh — Whale', emoji: '🐋' },
  { id: 'fc-x', domain: 'literacy', front: 'X', back: 'X-ray', phonics_notation: '/ks/ — ks — X-ray', emoji: '🩻' },
  { id: 'fc-y', domain: 'literacy', front: 'Y', back: 'Yarn', phonics_notation: '/j/ — yuh — Yarn', emoji: '🧶' },
  { id: 'fc-z', domain: 'literacy', front: 'Z', back: 'Zebra', phonics_notation: '/z/ — zzz — Zebra', emoji: '🦓' },
  // Math flashcards
  { id: 'fc-m1', domain: 'math', front: '1 + 1', back: '2', emoji: '✌️' },
  { id: 'fc-m2', domain: 'math', front: '2 + 2', back: '4', emoji: '🍀' },
  { id: 'fc-m3', domain: 'math', front: '3 + 2', back: '5', emoji: '🖐️' },
  { id: 'fc-m4', domain: 'math', front: '5 + 5', back: '10', emoji: '🔟' },
  { id: 'fc-m5', domain: 'math', front: '10 - 3', back: '7', emoji: '🌈' },
  { id: 'fc-m6', domain: 'math', front: '4 + 3', back: '7', emoji: '⭐' },
  { id: 'fc-m7', domain: 'math', front: '6 + 4', back: '10', emoji: '🎯' },
  { id: 'fc-m8', domain: 'math', front: '8 - 2', back: '6', emoji: '🎲' },
  { id: 'fc-m9', domain: 'math', front: '9 + 1', back: '10', emoji: '🏆' },
  { id: 'fc-m10', domain: 'math', front: '7 - 4', back: '3', emoji: '🔺' },
  // Science flashcards
  { id: 'fc-s1', domain: 'science', front: 'What falls from clouds?', back: 'Rain', emoji: '🌧️' },
  { id: 'fc-s2', domain: 'science', front: 'What gives us light during the day?', back: 'The Sun', emoji: '☀️' },
  { id: 'fc-s3', domain: 'science', front: 'What do plants need to grow?', back: 'Water, sunlight, and soil', emoji: '🌱' },
  { id: 'fc-s4', domain: 'science', front: 'How many legs does an insect have?', back: '6 legs', emoji: '🐛' },
  { id: 'fc-s5', domain: 'science', front: 'What season comes after winter?', back: 'Spring', emoji: '🌸' },
  // Social Studies flashcards
  { id: 'fc-ss1', domain: 'social-studies', front: 'Who helps put out fires?', back: 'Firefighters', emoji: '🚒' },
  { id: 'fc-ss2', domain: 'social-studies', front: 'Where do you go to borrow books?', back: 'The library', emoji: '📚' },
  { id: 'fc-ss3', domain: 'social-studies', front: 'What is a map?', back: 'A picture that shows where places are', emoji: '🗺️' },
  // SEL flashcards
  { id: 'fc-sel1', domain: 'social-emotional', front: 'What can you do when you feel angry?', back: 'Take deep breaths', emoji: '😤' },
  { id: 'fc-sel2', domain: 'social-emotional', front: 'Is it okay to cry?', back: 'Yes! All feelings are okay.', emoji: '😢' },
  { id: 'fc-sel3', domain: 'social-emotional', front: 'What does "kind" mean?', back: 'Being nice and caring to others', emoji: '💕' },
  // Executive Function flashcards
  { id: 'fc-ef1', domain: 'executive-function', front: 'What should you do before starting a task?', back: 'Make a plan!', emoji: '📋' },
  { id: 'fc-ef2', domain: 'executive-function', front: 'What helps you remember things?', back: 'Writing them down or repeating them', emoji: '🧠' },
  { id: 'fc-ef3', domain: 'executive-function', front: 'What does "taking turns" mean?', back: 'Waiting for your turn patiently', emoji: '🔄' },
];
